name: Deploy to ghcr.io
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docker image
        uses: GlueOps/github-actions-build-push-containers@v0.4.4